global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "microservices"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-api:8000"]
        labels:
          app_name: "auth"
      - targets: ["candidate-api:8000"]
        labels:
          app_name: "candidate"
      - targets: ["employer-api:8000"]
        labels:
          app_name: "employer"
      - targets: ["file-api:8000"]
        labels:
          app_name: "file"
      - targets: ["search-api:8000"]
        labels:
          app_name: "search"
      - targets: ["bot-api:8000"]
        labels:
          app_name: "bot"