"""Add English and About_Me

Revision ID: 9ac0297e774d
Revises: 48153e5fb352
Create Date: 2026-02-22 09:36:46.404801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac0297e774d'
down_revision: Union[str, Sequence[str], None] = '48153e5fb352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


english_level_enum = sa.Enum(
    'A1', 'A2', 'B1', 'B2', 'C1', 'C2',
    name='englishlevel'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    english_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'candidates',
        sa.Column('english_level', english_level_enum, nullable=True)
    )
    op.add_column(
        'candidates',
        sa.Column('about_me', sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'about_me')
    op.drop_column('candidates', 'english_level')
    english_level_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
